engines:
  phpmd:
    enabled: true
    checks:
      Naming/ShortVariable CleanCode/BooleanArgumentFlag CleanCode/StaticAccess UnusedFormalParameter:
        enabled: false
  duplication:
      enabled: true
      config:
        languages:
        - php
ratings:
  paths:
  - Classes/**
exclude_paths:
- Build/**/*
- Configuration/**/*
- Resources/**/*
- Tests/**/*