language: php

php:
  - '7.0'

sudo: true

services:
  - rabbitmq

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer --version
  - git config --global user.name "Dustin Kinney"
  - git config --global user.email "dustin@kinney.ws"

install:
  - sudo rabbitmq-plugins enable rabbitmq_management
  - sudo service rabbitmq-server restart
  - mkdir $HOME/bin && wget http://localhost:15672/cli/rabbitmqadmin -O $HOME/bin/rabbitmqadmin && chmod +x $HOME/bin/rabbitmqadmin && export PATH="$HOME/bin:$PATH"

before_script:
  - phpenv config-rm xdebug.ini;
  - composer install -o;

script:
  - >
    echo;
    echo "Running test suite";
    ./Build/runTests.sh;
